version: "3.9"
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8888:8888"
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
